Repository uob-group-10-mynt/mynt-finance-banking-app, pull requests merged in 2024-06, with the labels that each got.

#23 docs/git strategy
  git branch overview.png
  git_branch_strategies.md
Labels: documentation

#26 fix/global exception handler
  backend/src/main/java/com/mynt/mynt/util/dto/ResultResponseDTO.java
  backend/src/main/java/com/mynt/mynt/util/exceptions/ErrorResponse.java
  backend/src/main/java/com/mynt/mynt/util/exceptions/GlobalExceptionHandler.java
Labels: fix

#27 test: setup Cypress and first test
  frontend/cypress.config.js
  frontend/cypress/e2e/helloTest.cy.js
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/commands.js
  frontend/cypress/support/e2e.js
  frontend/package-lock.json
  frontend/package.json
Labels: init

#34 [feat]: Added environment variables in GitHub Action file to integrate DB from backend
  .github/workflows/backend-test.yml
Labels: enhancement

#37 [feat] Add dark mode option & refactor with Chakra UI
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app.js
  frontend/src/index.css
  frontend/src/remittance.js
  frontend/src/theme.js
Labels: enhancement

#38 Refactor/frontend remittances 1
  backend/build.gradle
  backend/src/main/java/com/mynt/mynt/controller/UserController.java
  backend/src/main/java/com/mynt/mynt/dto/UserSignupRequest.java
  backend/src/main/java/com/mynt/mynt/service/UserService.java
  frontend/src/assets/styles/index.css
  frontend/src/components/CustomButton.js
  frontend/src/components/CustomInput.js
  frontend/src/components/CustomLabel.js
  frontend/src/pages/RemittancePage.js
Labels: refactor

#42 [rename]: Renamed app.js to App.js and changed index.js
  frontend/src/App.js
  frontend/src/index.js
  frontend/src/remittance.js
Labels: change, fix

#43 [fix]: Fixed 'id' to 'root' and the app should work
  frontend/src/index.js
Labels: bug, fix

#46 [feat]: Added useAxios hook
  frontend/package-lock.json
  frontend/package.json
  frontend/src/hooks/useAxios.js
Labels: enhancement

#74 [feat]: Added ErrorPage
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/error_404.png
  frontend/src/pages/ErrorPage.js
  frontend/webpack.config.js
Labels: enhancement

#82 [feat]: Added CI for frontend
  .github/workflows/frontend-test.yml
Labels: enhancement

#83 [update]: Updated routes with new path
  frontend/src/utils/appRouter.js
Labels: enhancement
