Repository uob-group-10-mynt/mynt-finance-banking-app, pull requests merged in 2024-08, with the labels that each got.

#214 [feat]: Added conversion and confirm page
  frontend/src/App.js
  frontend/src/contexts/Conversion.js
  frontend/src/hooks/useConversion.js
  frontend/src/pages/Conversion/ConversionConfirmPage.js
  frontend/src/pages/Conversion/ConversionPage.js
  frontend/src/utils/AppRouter.js
Labels: enhancement

#226 [feat]: Added API integration on fx, accounts, and transaction
  frontend/src/components/util/Icon.js
  frontend/src/hooks/useAllCountryName.js
  frontend/src/hooks/useAxios.js
  frontend/src/hooks/useCurrencyDescription.js
  frontend/src/hooks/useCurrencySymbols.js
  frontend/src/hooks/useFormatAmount.js
  frontend/src/hooks/usePopularCountryName.js
  frontend/src/pages/Account/AccountPage.js
  frontend/src/pages/Conversion/ForeignExchangePage.js
  frontend/src/pages/Home.js
  frontend/src/utils/AppRouter.js
Labels: enhancement

#251 [refactor]: remove unused currency cloud endpoints
  backend/src/main/java/com/mynt/banking/currency_cloud/collect/demo/DemoFundingController.java
  backend/src/main/java/com/mynt/banking/currency_cloud/collect/funding/FundingController.java
  backend/src/main/java/com/mynt/banking/currency_cloud/convert/conversions/ConversionController.java
  backend/src/main/java/com/mynt/banking/currency_cloud/convert/rates/RateController.java
  backend/src/main/java/com/mynt/banking/currency_cloud/manage/accounts/AccountController.java
  backend/src/main/java/com/mynt/banking/currency_cloud/manage/contacts/ContactController.java
  backend/src/main/java/com/mynt/banking/currency_cloud/manage/reference/ReferenceController.java
  backend/src/main/java/com/mynt/banking/currency_cloud/manage/transactions/TransactionController.java
Labels: refactor

#266 [fix] Remove Mono except Flutterwave
  backend/src/main/java/com/mynt/banking/client/convert/conversions/MyntConversionsController.java
  backend/src/main/java/com/mynt/banking/client/convert/rates/MyntRatesController.java
  backend/src/main/java/com/mynt/banking/client/pay/payments/MyntPaymentsController.java
  backend/src/main/java/com/mynt/banking/config/SecurityConfig.java
  backend/src/main/java/com/mynt/banking/user/UserController.java
Labels: fix

#268 [fix]: electron app now works
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/NavigationLinks.js
  frontend/webpack.config.js
Labels: fix

#275 [fix]: enable http in capacitor config
  frontend/capacitor.config.ts
Labels: fix
